apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: expense
  labels: # replicaset labels
    app: frontend
    tier: web
    project: expense
spec:
  # modify replicas according to your case
  replicas: 2
  selector:
    matchLabels: # selector labels
      app: frontend
      tier: web
      project: expense
  template:
    metadata:
      labels:
        app: frontend
        tier: web
        project: expense
    spec:
      containers:
      - name: frontend
        image: joindevops/frontend:v1
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 100m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: expense
spec:
  #type: LoadBalancer
  selector:
    app: frontend
    tier: web
    project: expense
  ports:
  - name: frontend-svcport
    protocol: TCP
    port: 80 #service port
    targetPort: 80 # container port
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: frontend
  namespace: expense
spec:
  maxReplicas: 5
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend
  targetCPUUtilizationPercentage: 10
---
---
apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
   name: frontend
   namespace: expense
spec:
  serviceRef:
    name: frontend # route traffic to the nginx
    port: 80
  targetGroupARN: arn:aws:elasticloadbalancing:us-east-1:481155270892:targetgroup/expense-vpc-dev/01a88594fb686b43
  targetType: ip


