apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: expense
  labels: # replicaset labels
    app: mysql
    tier: db
    project: expense
spec:
  # modify replicas according to your case
  replicas: 1
  selector:
    matchLabels: # selector labels
      app: mysql
      tier: db
      project: expense
  template:
    metadata:
      labels:
        app: mysql
        tier: db
        project: expense
    spec:
      containers:
      - name: mysql
        image: venkat5555/mysql:v1
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: expense
spec:
  selector:
    app: mysql
    tier: db
    project: expense
  ports:
  - name: mysql-svcport
    protocol: TCP
    port: 3306 #service port
    targetPort: 3306 # container port



